### ISSUE TITLE
URL string is not converted into link

### ISSUE THREAD

**Issue by hyuki** [mattn/bsky#16]
When text containing a URL is posted, the part of the string that is the URL does not turn into a link.

However, thumbnail images do appear and become links (normal behavior). 

This issue persists regardless of whether the text's line breaks are LF or CR LF.

sample.txt:

```
This is a test.

https://example.com

```

session:

```
$ sw_vers
ProductName:		macOS
ProductVersion:		14.1.2
BuildVersion:		23B92
$ go install github.com/mattn/bsky@latest
$ bsky --version
bsky version 0.0.52
$ bsky login HANDLE PASSWORD
$ cat sample.txt | bsky post --stdin
```

result:

![image](https://github.com/mattn/bsky/assets/37487606/2cb3baf6-a604-4655-a874-753b41df6efe)

refer:

https://bsky.app/profile/hyuki.net/post/3kgryojjwcg2x

**Comment by hyuki** [comment]
[sample.txt](https://github.com/mattn/bsky/files/13699543/sample.txt)

**Comment by hyuki** [comment]
I received information stating, ["Links will not be added unless link information is attached to facets. Therefore, it is necessary to parse the text and specify where the links are located."](https://bsky.app/profile/nnabeyang.bsky.social/post/3kgs5plzq3y26)

cf. https://github.com/bluesky-social/atproto/blob/main/lexicons/app/bsky/feed/post.json#L19-L22

**Comment by mattn** [comment]
ひとまず修正を入れました。

https://bsky.app/profile/mattn.bsky.social/post/3kgt4v4llow2g

https://bsky.app/profile/mattn.bsky.social/post/3kgt4yokjut2l

しばらく触ってちゃんと動いてそうならマージします。
