### ISSUE TITLE
No issue, just thank you :)

### ISSUE THREAD

**Issue by eddelbuettel** [mattn/bsky#24]
I was checking whether hash tags were supported ... and delighted to see you just added it.

Last time I picked a binary from the releases.  But given `go` is on my Linux box I just built.  Very nice (to a non-Go programmer).  

So big thank you and feel free to close this :)

**Comment by eddelbuettel** [comment]
And to prove first bot generated skeet _with tag_:

![image](https://github.com/mattn/bsky/assets/673121/1f354e50-ed06-4016-b5eb-f4ebc3684e21)

whereas the preceeding one missed it:

![image](https://github.com/mattn/bsky/assets/673121/603d232c-7dc4-4901-bfe5-dac6a735e68a)

Very nice indeed!

**Comment by mattn** [comment]
:+1:  Thank you.
