### ISSUE TITLE
usage issue : comma in image name / text message with minus / text message with return to the line 

### ISSUE THREAD

**Issue by fredmo** [mattn/bsky#29]
Hello

I remark the following issues : 

bsky post -image "my_picture,project.jpg" "- topic1
- topic2
- topic3
"

1/
In the picture name, if there is a comma : the bsky will look for "my_picture," and miss the rest of the filename.
It seems to be linked to : 
   --image value, -i value [ --image value, -i value ]      

the commit could be in the filename, it s not a advised separator

2/
In the message, I remark , by doing as the example 
- topic1  =>  flag provided but not defined: - topic1
A message can't start with a "-" ? 

3/ 
the return to the line seems not managed? 
my lines seem ignored ?
- topic2
- topic3

**Comment by mattn** [comment]
About 3

You can use "--" 

```
bsky post -- "- topic1
topic2
topic3
"
```

In general UNIX command line programs, arguments after -- are not treated as flags, even if they start with -.

**Comment by mattn** [comment]
About 1

Now I fixed in https://github.com/mattn/bsky/commit/4f885a8e7e5ee0b52fe06ad9eafd25c4e03faea9

**Comment by mattn** [comment]
So closing.

**Comment by fredmo** [comment]
Thank you!
