### ISSUE TITLE
feature request: json support for notification call

### ISSUE THREAD

**Issue by dune73** [mattn/bsky#40]
```
$ bsky notification --json
Incorrect Usage: flag provided but not defined: -json
```

The notification call is very useful. It would be even more useful if the output could be filtered systematically, since the standard Bluesky gui does not allow to filter notifications (like filter away the "followed you" messages).

Filtering can work on the TXT output, but it's cleaner on json.

**Comment by mattn** [comment]
added in last change.

**Comment by dune73** [comment]
Awesome. Thank you.
