### ISSUE TITLE
OGP thumbnail is not shown

### ISSUE THREAD

**Issue by hyuki** [mattn/bsky#6]
OGP thumbnail is not shown when I posted URL with bsky version 0.0.26.

```
$ bsky post 'https://joinmastodon.org'
```

When posting URL with a thumbnail via staging or GUI client, the user explicitly specifies whether to display the OGP thumbnail or not by using the `Add Link` button (See figure below).

How can I specify that in bsky CLI?

![image](https://user-images.githubusercontent.com/37487606/233819998-719cb76b-2d5d-4109-88c6-f4292777462f.png)

**Comment by mattn** [comment]
Supported link-card. Now bsky would add a link with thumbnail for 1st URL.
